add　練習課題03の要件を満たす動作
Odachannnn/quelcode-php pull request #3
Opened 2020-06-04 04:31 UTC by Odachannnn

1. 参考にしたサイト
組み合わせについて
https://stabucky.com/wp/archives/2188

2020-06-04 07:16 UTC, piasoratech requested changes
動作は問題ありませんでした。
内容についてはコメントしたので確認をお願いします。

2020-06-04 07:16 UTC, piasoratech commented on html/php-pre-challenge3/index.php
> +    } elseif ($pick === 1) {
好みの問題かもしれませんが、早期returnを使う場合はそれだけでif文を完結させたほうが良いです。

2020-06-04 07:16 UTC, piasoratech commented on html/php-pre-challenge3/index.php
> +function comb($array, $pick)
関数の命名はどんな処理のをするのか明確にわかる命名にしましょう

2020-06-04 07:16 UTC, piasoratech commented on html/php-pre-challenge3/index.php
> +            $sum = $sum + $value;
+=を使いましょう

2020-06-04 09:04 UTC, Yuzunoha commented on html/php-pre-challenge3/index.php
> +echo json_encode($json);
```suggestion
echo json_encode($json);

```
ファイルの最後で1回改行しましょう！
最後に改行が無いと文だとみなされないため。

2020-06-04 09:25 UTC, Yuzunoha commented on html/php-pre-challenge3/index.php
> +} //ループ毎に型変換するより一括で変換した方が処理の回数減っていいのだろうけれど、配列の値を一括で型変換するやり方が見つけられず。。
修正不要ですが最近はラムダ式で配列の要素を変換するようです。

```php
array_walk($values, function (&$value) {
    // 配列の要素全てに変換が適用される
    $value = intval($value); 
});
```

2020-06-05 02:17 UTC, Yuzunoha approved these changes
OKです！！承認しました！！！

2020-06-10 07:02 UTC, merged